name: Update README.md

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '>=3.9'

      # Install dependencies
      - name: Install mdft
        run: pip install mdft

      # Run mdft on README.md
      - name: Process README.md with mdft
        run: |
          python3 -m mdft README.md

      # Show generated README.md file
      - name: Show README.md
        run: cat README.md

      # Check for changes
      - name: Check for changes in README.md
        id: check_changes
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "README_CHANGED=true" >> $GITHUB_OUTPUT
            echo "Changes detected"
          else
            echo "README_CHANGED=false" >> $GITHUB_OUTPUT
            echo "No changes detected"
          fi

      # Commit and push changes if README.md has changed
      - name: Commit and push changes
        if: steps.check_changes.outputs.README_CHANGED == 'true'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README.md"
          git push
